new_employees_data = [
    {
        "NIK":  "1234567890",                                                                       
        "name": "Bruno",
        "age": 22,
        "gender":  "Male",
        "domicile":  "Jakarta",
        "position": "Software Engineer",
    },
    {
        "NIK":  "1111111111",
        "name": "Rafael",
        "age": 28,
        "gender":  "Male",
        "domicile":  "Surabaya",
        "position": "Data Scientist",
    },
    {
        "NIK":  "2222222222",
        "name": "Lila Vania",
        "age": 24,
        "gender":  "Female",
        "domicile":  "Malang",
        "position": "Software Engineer",
    },
    {
        "NIK":  "3333333333",
        "name": "Rohan Rizky",
        "age": 24,
        "gender":  "Male",
        "domicile":  "Bogor",
        "position": "UX/UI Designer",
    },
    {
        "NIK":  "4444444444",
        "name": "Aisha Maria",
        "age": 25,
        "gender":  "Female",
        "domicile":  "Depok",
        "position": "Data Scientist",
    },
    {
        "NIK":  "5555555555",
        "name": "Kaito Reihan",
        "age": 28,
        "gender":  "Male",
        "domicile":  "Tangerang",
        "position": "DevOps Engineer",
    },
    {
        "NIK":  "6666666666",
        "name": "Ferro Adrian",
        "age": 30,
        "gender":  "Male",
        "domicile":  "Jakarta",
        "position": "Full Stack Developer",
    },
    {
        "NIK":  "7777777777",
        "name": "Eitan Subhon",
        "age": 22,
        "gender":  "Male",
        "domicile":  "Bandung",
        "position": "Data Analyst",
    },
    {
        "NIK":  "8888888888",
        "name": "Lutfiah Anum",
        "age": 26,
        "gender":  "Female",
        "domicile":  "Surabaya",
        "position": "Cloud Engineer",
    },
    {
        "NIK":  "9999999999",
        "name": "Luna Basri",
        "age": 25,
        "gender":  "Female",
        "domicile":  "Bandung",
        "position": "Software Engineer",
    }
]